version: "3.4"

services:
  app:
    image: cicd-started
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:3001 || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5